### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by rshkv** [thefrenchhouse/spotify-graphql#30]
I'm using your library to query tracks, and I would like to display their album covers. I took from [this](https://github.com/thefrenchhouse/spotify-graphql/blob/master/lib/schema.ts), that your album's don't include images.

Is images something you intend to add in the near future? Or can you point me to what I'd have to do to add them to the schema? This is my first time with GraphQL, but I know that the SpotifyApi includes images when you query tracks or albums. I assume it wouldn't need extra calls.

Would appreciate 🙂.

**Comment by wittydeveloper** [comment]
Hi @rshkv,

That's a good request, I'll plan to implement the images for all types that need it by the end of week.

See #31

Cheers !

**Comment by rshkv** [comment]
Awesome! Thank you very much, @wittydeveloper.

**Comment by wittydeveloper** [comment]
@rshkv , it's released !

See https://github.com/thefrenchhouse/spotify-graphql/blob/master/CHANGELOG.md#110-2017-03-15

You can now do the following : 


```
query {
    track(id: "1zHlj4dQ8ZAtrayhuDDmk4") {
        id
        name
        album {
            id
            name
            images {
                url
                height
                width
            }
        }
    }
}
```


Images are available on following types : `Artist`, `Playlist`, `Album` and `User`



Tell me if you have other requests, I'll be happy to add some features!

**Comment by rshkv** [comment]
Thanks!
